#!/usr/bin/env bash

# s_push: Push to multiple git remotes in order
# Usage: s_push remote1 remote2 remote3 ...
# Example: s_push origin backuprepo github
# Each remote will be pushed with 'git push <remote>'

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 remote1 [remote2 ...]"
    exit 1
fi

for remote in "$@"; do
    echo "Pushing to '$remote'..."
    git push "$remote"
    if [ $? -ne 0 ]; then
        echo "Push to '$remote' failed!"
    else
        echo "Push to '$remote' succeeded."
    fi
    echo "----------------------------------"
done

echo "All pushes attempted."
